Verify checksums in update script

diff --git a/update b/update
--- a/update
+++ b/update
@@ -33,8 +33,8 @@ fi
 RAW_CURRENT_VERSION=$(echo "$CURRENT_VERSION" | sed "s/-portable//")
 
 if [ "$LATEST_VERSION_TAG" == "$RAW_CURRENT_VERSION" ]; then
-    log_done "You are already using the latest version of Prasmoid (v$RAW_CURRENT_VERSION)."
-    exit 0
+     log_done "You are already using the latest version of Prasmoid (v$RAW_CURRENT_VERSION)."
+     exit 0
 fi
 
 IS_PORTABLE=false
@@ -50,6 +50,7 @@ fi
 
 if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
     log_fail "No suitable binary found for version $LATEST_VERSION_TAG."
+    exit 1
 fi
 
 log_step "Downloading v$LATEST_VERSION_TAG..."
@@ -61,6 +62,26 @@ if [ $? -ne 0 ]; then
     log_fail "Download failed."
 fi
 log_done "Download complete."
+
+log_step "Verifying checksum..."
+SHA256_PASSED=false
+# move to dir containing the temp file, make 2nd temp file named correctly for sha256sum
+pushd $(dirname "$TEMP_FILE")
+if $IS_PORTABLE; then
+    TEMP_EXE="prasmoid"
+else
+    TEMP_EXE="prasmoid-portable"
+fi
+cp $(basename "$TEMP_FILE") $TEMP_EXE
+SHA256_URL=$(echo "$LATEST_RELEASE_INFO" | jq -r '.assets[] | select(.name == "SHA256SUMS") | .browser_download_url')
+if curl -L "$SHA256_URL" | sha256sum -c --ignore-missing --status - ; then
+    log_done "Checksum passed"
+else
+    log_fail "Checksum failed!"
+fi
+rm $TEMP_EXE
+popd
+
 
 chmod +x "$TEMP_FILE"
 
